openapi: 3.0.0
info:
  title: Malaka ERP API
  version: 1.0.0
paths:
  /masterdata/users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /masterdata/users/{id}:
    get:
      summary: Get user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      summary: Update user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      summary: Delete user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User deleted successfully
  /masterdata/users/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
components:
  schemas:
    BaseModel:
      type: object
      properties:
        id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    User:
      allOf:
        - $ref: '#/components/schemas/BaseModel'
        - type: object
          properties:
            username:
              type: string
            email:
              type: string
            company_id:
              type: string
            role:
              type: string
    CreateUserRequest:
      type: object
      required:
        - username
        - password
        - email
        - company_id
        - role
      properties:
        username:
          type: string
        password:
          type: string
          format: password
        email:
          type: string
          format: email
        company_id:
          type: string
        role:
          type: string
    UpdateUserRequest:
      type: object
      required:
        - username
        - password
        - email
        - company_id
        - role
      properties:
        username:
          type: string
        password:
          type: string
          format: password
        email:
          type: string
          format: email
        company_id:
          type: string
        role:
          type: string
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
          format: password