'use client'

import React, { useState, useMemo, useEffect } from 'react'
import { TwoLevelLayout } from '@/components/ui/two-level-layout'
import { Header } from '@/components/ui/header'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { TanStackDataTable, TanStackColumn } from '@/components/ui/tanstack-data-table'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Label } from '@/components/ui/label'
import { useToast } from '@/components/ui/toast'
import { HugeiconsIcon } from '@hugeicons/react'
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import {
    File01Icon,
    Download01Icon,
    Calendar02Icon,
    Search01Icon,
    PlusSignIcon,
    Presentation02Icon,
    MoreHorizontalIcon
} from '@hugeicons/core-free-icons'
import { BookmarkToggle } from '@/components/ui/bookmark-toggle'
import { financeReportService, type FinanceReport } from '@/services/finance'

export default function FinanceReportsPage() {
    const { addToast } = useToast()
    const [searchTerm, setSearchTerm] = useState('')
    const [typeFilter, setTypeFilter] = useState<string>('all')
    const [isGenerateModalOpen, setIsGenerateModalOpen] = useState(false)
    const [reports, setReports] = useState<FinanceReport[]>([])
    const [loading, setLoading] = useState(true)
    const [mounted, setMounted] = useState(false)

    useEffect(() => { setMounted(true) }, [])

    useEffect(() => {
        async function fetchData() {
            try {
                setLoading(true)
                const data = await financeReportService.getAll()
                setReports(data)
            } catch (err) {
                console.error('Failed to fetch reports:', err)
            } finally {
                setLoading(false)
            }
        }
        fetchData()
    }, [])

    // --- Stats ---
    const stats = useMemo(() => {
        const totalReports = reports.length
        const readyReports = reports.filter(r => r.status === 'ready').length
        const lastGenerated = mounted && reports.length > 0 ? new Date(reports[0].created_at).toLocaleDateString() : '-'
        return { totalReports, readyReports, lastGenerated }
    }, [reports, mounted])

    // --- Data ---
    const filteredData = useMemo(() => {
        let data = reports
        if (searchTerm) {
            const lower = searchTerm.toLowerCase()
            data = data.filter(item => item.report_name.toLowerCase().includes(lower))
        }
        if (typeFilter !== 'all') {
            data = data.filter(item => item.type === typeFilter)
        }
        return data
    }, [searchTerm, typeFilter, reports])

    // --- Columns ---
    const columns: TanStackColumn<FinanceReport>[] = [
        {
            id: 'reportName',
            header: 'Report Name',
            accessorKey: 'report_name',
            cell: ({ row }) => (
                <div className="flex flex-col">
                    <span className="font-medium text-sm">{row.original.report_name}</span>
                    <span className="text-xs text-muted-foreground">{row.original.type}</span>
                </div>
            )
        },
        {
            id: 'period',
            header: 'Period',
            accessorKey: 'period',
            cell: ({ row }) => (
                <div className="flex items-center gap-2">
                    <HugeiconsIcon icon={Calendar02Icon} className="w-3 h-3 text-muted-foreground" />
                    <span className="text-sm">{row.original.period}</span>
                </div>
            )
        },
        {
            id: 'generatedBy',
            header: 'Generated By',
            accessorKey: 'generated_by',
            cell: ({ row }) => <span className="text-sm">{row.original.generated_by}</span>
        },
        {
            id: 'generatedAt',
            header: 'Date',
            accessorKey: 'created_at',
            cell: ({ row }) => <span className="text-sm text-muted-foreground">{mounted && row.original.created_at ? new Date(row.original.created_at).toLocaleDateString() : '-'}</span>
        },
        {
            id: 'status',
            header: 'Status',
            accessorKey: 'status',
            cell: ({ row }) => {
                const config: Record<string, { label: string; color: string }> = {
                    ready: { label: 'Ready', color: 'bg-green-100 text-green-800' },
                    processing: { label: 'Processing', color: 'bg-blue-100 text-blue-800' },
                    failed: { label: 'Failed', color: 'bg-red-100 text-red-800' }
                }
                const s = config[row.original.status] || { label: row.original.status, color: 'bg-gray-100 text-gray-800' }
                return <Badge className={`${s.color} border-0 capitalize`}>{s.label}</Badge>
            }
        },
        {
            id: 'actions',
            header: '',
            cell: ({ row }) => (
                <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                        <Button variant="ghost" className="h-8 w-8 p-0">
                            <span className="sr-only">Open menu</span>
                            <HugeiconsIcon icon={MoreHorizontalIcon} className="h-4 w-4" />
                        </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                        <DropdownMenuLabel>Actions</DropdownMenuLabel>
                        <DropdownMenuItem
                            disabled={row.original.status !== 'ready'}
                            onClick={() => console.log('Downloading', row.original.id)}
                        >
                            <HugeiconsIcon icon={Download01Icon} className="h-4 w-4 mr-2" />
                            Download
                        </DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem>View Details</DropdownMenuItem>
                        <DropdownMenuItem className="text-red-600">Delete</DropdownMenuItem>
                    </DropdownMenuContent>
                </DropdownMenu>
            )
        }
    ]

    return (
        <TwoLevelLayout>
            <Header
                title="Finance Reports"
                description="Generate and view financial statements and reports"
                breadcrumbs={[
                    { label: 'Finance', href: '/finance' },
                    { label: 'Reports' }
                ]}
                actions={
                    <div className="flex items-center gap-2">
                        <BookmarkToggle itemId="finance-reports" />
                        <Button onClick={() => setIsGenerateModalOpen(true)}>
                            <HugeiconsIcon icon={PlusSignIcon} className="w-4 h-4 mr-2" />
                            Generate Report
                        </Button>
                    </div>
                }
            />

            <div className="flex-1 p-6 space-y-6">
                {/* Stats */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <Card>
                        <CardContent className="p-4 flex items-center justify-between">
                            <div>
                                <p className="text-sm font-medium text-muted-foreground">Total Reports</p>
                                <p className="text-2xl font-bold">{stats.totalReports}</p>
                            </div>
                            <div className="h-10 w-10 bg-blue-100 dark:bg-blue-900/20 rounded-lg flex items-center justify-center">
                                <HugeiconsIcon icon={File01Icon} className="h-5 w-5 text-blue-600 dark:text-blue-400" />
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardContent className="p-4 flex items-center justify-between">
                            <div>
                                <p className="text-sm font-medium text-muted-foreground">Available to Download</p>
                                <p className="text-2xl font-bold">{stats.readyReports}</p>
                            </div>
                            <div className="h-10 w-10 bg-green-100 dark:bg-green-900/20 rounded-lg flex items-center justify-center">
                                <HugeiconsIcon icon={Download01Icon} className="h-5 w-5 text-green-600 dark:text-green-400" />
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardContent className="p-4 flex items-center justify-between">
                            <div>
                                <p className="text-sm font-medium text-muted-foreground">Last Generated</p>
                                <p className="text-2xl font-bold">{stats.lastGenerated}</p>
                            </div>
                            <div className="h-10 w-10 bg-purple-100 dark:bg-purple-900/20 rounded-lg flex items-center justify-center">
                                <HugeiconsIcon icon={Presentation02Icon} className="h-5 w-5 text-purple-600 dark:text-purple-400" />
                            </div>
                        </CardContent>
                    </Card>
                </div>

                {/* Filters */}
                <div className="flex items-center justify-between gap-2">
                    <div className="relative w-64">
                        <HugeiconsIcon icon={Search01Icon} className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                        <Input
                            placeholder="Search reports..."
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                            className="pl-9 h-9"
                        />
                    </div>
                    <div className="flex items-center gap-2">
                        <Select value={typeFilter} onValueChange={setTypeFilter}>
                            <SelectTrigger className="w-[180px] h-9">
                                <SelectValue placeholder="Report Type" />
                            </SelectTrigger>
                            <SelectContent>
                                <SelectItem value="all">All Types</SelectItem>
                                <SelectItem value="Balance Sheet">Balance Sheet</SelectItem>
                                <SelectItem value="Income Statement">Income Statement</SelectItem>
                                <SelectItem value="Cash Flow">Cash Flow</SelectItem>
                                <SelectItem value="Budget Variance">Budget Variance</SelectItem>
                            </SelectContent>
                        </Select>
                    </div>
                </div>

                {/* Table */}
                {loading ? (
                    <div className="flex items-center justify-center py-12">
                        <div className="text-muted-foreground">Loading reports...</div>
                    </div>
                ) : (
                    <TanStackDataTable
                        data={filteredData}
                        columns={columns}
                        enableRowSelection
                        showColumnToggle={false}
                    />
                )}
            </div>

            {/* Generate Modal Placeholder */}
            <Dialog open={isGenerateModalOpen} onOpenChange={setIsGenerateModalOpen}>
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle>Generate New Report</DialogTitle>
                    </DialogHeader>
                    <div className="space-y-4 py-4">
                        <div className="space-y-2">
                            <Label>Report Type</Label>
                            <Select>
                                <SelectTrigger><SelectValue placeholder="Select Type" /></SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="bs">Balance Sheet</SelectItem>
                                    <SelectItem value="pl">Income Statement</SelectItem>
                                    <SelectItem value="cf">Cash Flow</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                        <div className="space-y-2">
                            <Label>Period</Label>
                            <Select>
                                <SelectTrigger><SelectValue placeholder="Select Period" /></SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="last_month">Last Month</SelectItem>
                                    <SelectItem value="this_quarter">Current Quarter</SelectItem>
                                    <SelectItem value="ytd">Year to Date</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                        <div className="space-y-2">
                            <Label>Format</Label>
                            <div className="flex gap-4">
                                <div className="flex items-center space-x-2">
                                    <input type="radio" id="pdf" name="format" defaultChecked className="h-4 w-4" />
                                    <label htmlFor="pdf">PDF</label>
                                </div>
                                <div className="flex items-center space-x-2">
                                    <input type="radio" id="excel" name="format" className="h-4 w-4" />
                                    <label htmlFor="excel">Excel</label>
                                </div>
                            </div>
                        </div>
                        <div className="flex justify-end gap-2 pt-4">
                            <Button variant="outline" onClick={() => setIsGenerateModalOpen(false)}>Cancel</Button>
                            <Button onClick={() => {
                                addToast({ type: 'success', title: 'Report generation started' })
                                setIsGenerateModalOpen(false)
                            }}>Generate</Button>
                        </div>
                    </div>
                </DialogContent>
            </Dialog>
        </TwoLevelLayout>
    )
}
