-- Chart of Accounts seed data
INSERT INTO chart_of_accounts (account_code, account_name, account_type, parent_id) VALUES
('1000', 'HARTA', 'ASSET', NULL),
('1100', 'Harta Lancar', 'ASSET', (SELECT id FROM chart_of_accounts WHERE account_code = '1000')),
('1110', 'Kas dan Bank', 'ASSET', (SELECT id FROM chart_of_accounts WHERE account_code = '1100')),
('1111', 'Kas Kecil', 'ASSET', (SELECT id FROM chart_of_accounts WHERE account_code = '1110')),
('1112', 'Bank BCA Jakarta', 'ASSET', (SELECT id FROM chart_of_accounts WHERE account_code = '1110')),
('1113', 'Bank Mandiri Surabaya', 'ASSET', (SELECT id FROM chart_of_accounts WHERE account_code = '1110')),
('1120', 'Piutang Usaha', 'ASSET', (SELECT id FROM chart_of_accounts WHERE account_code = '1100')),
('1121', 'Piutang Dagang', 'ASSET', (SELECT id FROM chart_of_accounts WHERE account_code = '1120')),
('1122', 'Piutang Karyawan', 'ASSET', (SELECT id FROM chart_of_accounts WHERE account_code = '1120')),
('1130', 'Persediaan', 'ASSET', (SELECT id FROM chart_of_accounts WHERE account_code = '1100')),
('1131', 'Persediaan Sepatu', 'ASSET', (SELECT id FROM chart_of_accounts WHERE account_code = '1130')),
('1132', 'Persediaan Sandal', 'ASSET', (SELECT id FROM chart_of_accounts WHERE account_code = '1130')),
('1200', 'Harta Tetap', 'ASSET', (SELECT id FROM chart_of_accounts WHERE account_code = '1000')),
('1210', 'Tanah dan Bangunan', 'ASSET', (SELECT id FROM chart_of_accounts WHERE account_code = '1200')),
('1220', 'Kendaraan', 'ASSET', (SELECT id FROM chart_of_accounts WHERE account_code = '1200')),
('1230', 'Peralatan Kantor', 'ASSET', (SELECT id FROM chart_of_accounts WHERE account_code = '1200')),
('2000', 'HUTANG', 'LIABILITY', NULL),
('2100', 'Hutang Lancar', 'LIABILITY', (SELECT id FROM chart_of_accounts WHERE account_code = '2000')),
('2110', 'Hutang Usaha', 'LIABILITY', (SELECT id FROM chart_of_accounts WHERE account_code = '2100')),
('2120', 'Hutang Pajak', 'LIABILITY', (SELECT id FROM chart_of_accounts WHERE account_code = '2100')),
('2130', 'Hutang Gaji', 'LIABILITY', (SELECT id FROM chart_of_accounts WHERE account_code = '2100')),
('3000', 'MODAL', 'EQUITY', NULL),
('3100', 'Modal Saham', 'EQUITY', (SELECT id FROM chart_of_accounts WHERE account_code = '3000')),
('3200', 'Laba Ditahan', 'EQUITY', (SELECT id FROM chart_of_accounts WHERE account_code = '3000')),
('4000', 'PENDAPATAN', 'REVENUE', NULL),
('4100', 'Pendapatan Penjualan', 'REVENUE', (SELECT id FROM chart_of_accounts WHERE account_code = '4000')),
('4110', 'Penjualan Sepatu', 'REVENUE', (SELECT id FROM chart_of_accounts WHERE account_code = '4100')),
('4120', 'Penjualan Sandal', 'REVENUE', (SELECT id FROM chart_of_accounts WHERE account_code = '4100')),
('5000', 'BIAYA', 'EXPENSE', NULL),
('5100', 'Harga Pokok Penjualan', 'EXPENSE', (SELECT id FROM chart_of_accounts WHERE account_code = '5000')),
('5200', 'Biaya Operasional', 'EXPENSE', (SELECT id FROM chart_of_accounts WHERE account_code = '5000')),
('5210', 'Biaya Gaji', 'EXPENSE', (SELECT id FROM chart_of_accounts WHERE account_code = '5200')),
('5220', 'Biaya Sewa', 'EXPENSE', (SELECT id FROM chart_of_accounts WHERE account_code = '5200')),
('5230', 'Biaya Listrik', 'EXPENSE', (SELECT id FROM chart_of_accounts WHERE account_code = '5200')),
('5240', 'Biaya Transportasi', 'EXPENSE', (SELECT id FROM chart_of_accounts WHERE account_code = '5200'));