-- Dynamic OLAP Reports seed data
INSERT INTO dynamic_olap_reports (report_code, report_name, report_category, description, data_source, sql_query, parameters, dimensions, measures, filters, sort_order, is_public, created_by, execution_count, avg_execution_time) VALUES
('RPT001', 'Analisis Penjualan per Periode', 'Penjualan', 'Laporan analisis penjualan berdasarkan periode waktu dan lokasi toko', 'sales_orders', 'SELECT store_id, DATE_TRUNC(''month'', order_date) as period, SUM(total_amount) as total_sales FROM sales_orders WHERE order_date BETWEEN $1 AND $2 GROUP BY store_id, DATE_TRUNC(''month'', order_date)', '{"start_date": "date", "end_date": "date"}', '["store_id", "period"]', '["total_sales"]', '{"status": ["COMPLETED", "PAID"]}', '{"period": "ASC", "total_sales": "DESC"}', true, (SELECT id FROM users WHERE email = 'manager@malaka.co.id' LIMIT 1), 25, 1250),
('RPT002', 'Inventory Movement Analysis', 'Inventory', 'Analisis pergerakan stok barang per kategori dan lokasi', 'stock_movements', 'SELECT warehouse_id, movement_type, SUM(quantity) as total_qty FROM stock_movements WHERE movement_date BETWEEN $1 AND $2 GROUP BY warehouse_id, movement_type', '{"start_date": "date", "end_date": "date"}', '["warehouse_id", "movement_type"]', '["total_qty"]', '{}', '{"warehouse_id": "ASC", "total_qty": "DESC"}', true, (SELECT id FROM users WHERE email = 'supervisor@malaka.co.id' LIMIT 1), 18, 980),
('RPT003', 'Customer Purchase Behavior', 'Customer', 'Analisis perilaku pembelian pelanggan berdasarkan demografi', 'sales_orders', 'SELECT c.city, COUNT(s.id) as order_count, AVG(s.total_amount) as avg_order FROM sales_orders s JOIN customers c ON s.customer_id = c.id WHERE s.order_date BETWEEN $1 AND $2 GROUP BY c.city', '{"start_date": "date", "end_date": "date"}', '["city"]', '["order_count", "avg_order"]', '{}', '{"order_count": "DESC"}', false, (SELECT id FROM users WHERE email = 'staff@malaka.co.id' LIMIT 1), 12, 1850),
('RPT004', 'Supplier Performance Report', 'Procurement', 'Laporan kinerja supplier berdasarkan ketepatan pengiriman dan kualitas', 'purchase_orders', 'SELECT supplier_id, COUNT(*) as total_orders, SUM(total_amount) as total_value FROM purchase_orders WHERE order_date BETWEEN $1 AND $2 GROUP BY supplier_id', '{"start_date": "date", "end_date": "date"}', '["supplier_id"]', '["total_orders", "total_value"]', '{"status": ["COMPLETED", "RECEIVED"]}', '{"total_value": "DESC"}', true, (SELECT id FROM users WHERE email = 'manager@malaka.co.id' LIMIT 1), 30, 720),
('RPT005', 'Financial Cash Flow Analysis', 'Finance', 'Analisis arus kas masuk dan keluar berdasarkan kategori', 'cash_receipts', 'SELECT receipt_type, SUM(amount) as total_amount FROM cash_receipts WHERE receipt_date BETWEEN $1 AND $2 GROUP BY receipt_type UNION SELECT disbursement_type, -SUM(amount) as total_amount FROM cash_disbursements WHERE disbursement_date BETWEEN $1 AND $2 GROUP BY disbursement_type', '{"start_date": "date", "end_date": "date"}', '["transaction_type"]', '["total_amount"]', '{}', '{"total_amount": "DESC"}', false, (SELECT id FROM users WHERE email = 'cashier@malaka.co.id' LIMIT 1), 8, 2100),
('RPT006', 'Employee Performance Dashboard', 'HR', 'Dashboard kinerja karyawan berdasarkan absensi dan produktivitas', 'employees', 'SELECT department, COUNT(*) as total_employees, AVG(basic_salary) as avg_salary FROM employees WHERE employment_status = ''ACTIVE'' GROUP BY department', '{}', '["department"]', '["total_employees", "avg_salary"]', '{"employment_status": ["ACTIVE"]}', '{"total_employees": "DESC"}', true, (SELECT id FROM users WHERE email = 'supervisor@malaka.co.id' LIMIT 1), 15, 850),
('RPT007', 'Product Category Performance', 'Product', 'Analisis performa penjualan berdasarkan kategori produk', 'sales_orders', 'SELECT a.category, COUNT(so.id) as order_count, SUM(so.total_amount) as total_sales FROM sales_orders so JOIN articles a ON so.article_id = a.id WHERE so.order_date BETWEEN $1 AND $2 GROUP BY a.category', '{"start_date": "date", "end_date": "date"}', '["category"]', '["order_count", "total_sales"]', '{}', '{"total_sales": "DESC"}', true, (SELECT id FROM users WHERE email = 'staff@malaka.co.id' LIMIT 1), 22, 1100),
('RPT008', 'Warehouse Utilization Report', 'Warehouse', 'Laporan utilisasi gudang dan kapasitas penyimpanan', 'stock_balances', 'SELECT warehouse_id, COUNT(*) as item_count, SUM(quantity) as total_qty FROM stock_balances WHERE quantity > 0 GROUP BY warehouse_id', '{}', '["warehouse_id"]', '["item_count", "total_qty"]', '{"quantity": "> 0"}', '{"total_qty": "DESC"}', true, (SELECT id FROM users WHERE email = 'manager@malaka.co.id' LIMIT 1), 10, 650),
('RPT009', 'Shipping Cost Analysis', 'Logistics', 'Analisis biaya pengiriman berdasarkan kurir dan tujuan', 'shipping_invoices', 'SELECT courier_id, destination, COUNT(*) as shipment_count, AVG(total_amount) as avg_cost FROM shipping_invoices WHERE invoice_date BETWEEN $1 AND $2 GROUP BY courier_id, destination', '{"start_date": "date", "end_date": "date"}', '["courier_id", "destination"]', '["shipment_count", "avg_cost"]', '{}', '{"avg_cost": "DESC"}', false, (SELECT id FROM users WHERE email = 'cashier@malaka.co.id' LIMIT 1), 14, 1400),
('RPT010', 'Sales Target vs Achievement', 'Sales', 'Perbandingan target penjualan dengan pencapaian aktual', 'sales_targets', 'SELECT employee_id, period_year, period_month, target_amount, actual_amount, (actual_amount/target_amount)*100 as achievement_pct FROM sales_targets WHERE period_year = $1', '{"year": "integer"}', '["employee_id", "period_year", "period_month"]', '["target_amount", "actual_amount", "achievement_pct"]', '{}', '{"achievement_pct": "DESC"}', true, (SELECT id FROM users WHERE email = 'supervisor@malaka.co.id' LIMIT 1), 35, 900);