-- Goods Receipts Seed Data
-- Indonesian realistic goods receipts for shoe manufacturing/retail business

-- Note: This assumes purchase_orders and warehouses exist with proper UUIDs
-- Using some fictional purchase order and warehouse IDs that would be generated by the app

INSERT INTO goods_receipts (
    id,
    purchase_order_id, 
    receipt_date,
    warehouse_id
) VALUES 
-- Main warehouse receipts (Jakarta)
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE supplier_id = (SELECT id FROM suppliers WHERE name LIKE '%PT Sepatu%' LIMIT 1) LIMIT 1),
    '2024-01-15 09:30:00+07:00',
    (SELECT id FROM warehouses WHERE name LIKE '%Jakarta%' OR name LIKE '%Main%' LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE supplier_id = (SELECT id FROM suppliers WHERE name LIKE '%CV Kulit%' LIMIT 1) LIMIT 1),
    '2024-01-16 10:15:00+07:00',
    (SELECT id FROM warehouses WHERE name LIKE '%Jakarta%' OR name LIKE '%Main%' LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE supplier_id = (SELECT id FROM suppliers WHERE name LIKE '%UD Bahan%' LIMIT 1) LIMIT 1),
    '2024-01-17 14:45:00+07:00',
    (SELECT id FROM warehouses WHERE name LIKE '%Jakarta%' OR name LIKE '%Main%' LIMIT 1)
),

-- Surabaya warehouse receipts
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE supplier_id = (SELECT id FROM suppliers WHERE name LIKE '%PT Manufaktur%' LIMIT 1) LIMIT 1),
    '2024-01-18 08:20:00+07:00',
    (SELECT id FROM warehouses WHERE name LIKE '%Surabaya%' LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE supplier_id = (SELECT id FROM suppliers WHERE name LIKE '%CV Dagang%' LIMIT 1) LIMIT 1),
    '2024-01-19 11:30:00+07:00',
    (SELECT id FROM warehouses WHERE name LIKE '%Surabaya%' LIMIT 1)
),

-- Bandung warehouse receipts
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE supplier_id = (SELECT id FROM suppliers WHERE name LIKE '%PT Tekstil%' LIMIT 1) LIMIT 1),
    '2024-01-20 13:10:00+07:00',
    (SELECT id FROM warehouses WHERE name LIKE '%Bandung%' LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE supplier_id = (SELECT id FROM suppliers WHERE name LIKE '%UD Rajut%' LIMIT 1) LIMIT 1),
    '2024-01-21 15:45:00+07:00',
    (SELECT id FROM warehouses WHERE name LIKE '%Bandung%' LIMIT 1)
),

-- Medan warehouse receipts
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE supplier_id = (SELECT id FROM suppliers WHERE name LIKE '%CV Plastik%' LIMIT 1) LIMIT 1),
    '2024-01-22 09:00:00+07:00',
    (SELECT id FROM warehouses WHERE name LIKE '%Medan%' LIMIT 1)
),

-- Recent receipts (last week)
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE status = 'approved' LIMIT 1),
    '2024-01-23 10:30:00+07:00',
    (SELECT id FROM warehouses LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE status = 'approved' LIMIT 1 OFFSET 1),
    '2024-01-24 14:20:00+07:00',
    (SELECT id FROM warehouses LIMIT 1 OFFSET 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE status = 'approved' LIMIT 1 OFFSET 2),
    '2024-01-25 11:15:00+07:00',
    (SELECT id FROM warehouses LIMIT 1 OFFSET 2)
),
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE status = 'approved' LIMIT 1 OFFSET 3),
    '2024-01-26 16:40:00+07:00',
    (SELECT id FROM warehouses LIMIT 1)
),

-- Today's receipts
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE status = 'approved' LIMIT 1 OFFSET 4),
    CURRENT_TIMESTAMP,
    (SELECT id FROM warehouses LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE status = 'approved' LIMIT 1 OFFSET 5),
    CURRENT_TIMESTAMP - INTERVAL '2 hours',
    (SELECT id FROM warehouses LIMIT 1 OFFSET 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE status = 'approved' LIMIT 1 OFFSET 6),
    CURRENT_TIMESTAMP - INTERVAL '4 hours',
    (SELECT id FROM warehouses LIMIT 1 OFFSET 2)
),

-- Future scheduled receipts (expected)
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE status = 'pending' LIMIT 1),
    CURRENT_TIMESTAMP + INTERVAL '1 day',
    (SELECT id FROM warehouses LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE status = 'pending' LIMIT 1 OFFSET 1),
    CURRENT_TIMESTAMP + INTERVAL '2 days',
    (SELECT id FROM warehouses LIMIT 1 OFFSET 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE status = 'pending' LIMIT 1 OFFSET 2),
    CURRENT_TIMESTAMP + INTERVAL '3 days',
    (SELECT id FROM warehouses LIMIT 1 OFFSET 2)
),
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE status = 'pending' LIMIT 1 OFFSET 3),
    CURRENT_TIMESTAMP + INTERVAL '5 days',
    (SELECT id FROM warehouses LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM purchase_orders WHERE status = 'pending' LIMIT 1 OFFSET 4),
    CURRENT_TIMESTAMP + INTERVAL '7 days',
    (SELECT id FROM warehouses LIMIT 1 OFFSET 1)
);