-- Warehouses seed data
-- 12 realistic Indonesian warehouses for shoe manufacturing/retail business

INSERT INTO warehouses (
    code, name, address, city, phone, manager, email, 
    type, capacity, current_stock, status, 
    zones, operating_hours, facilities, coordinates
) VALUES 
-- Main Warehouses (Jakarta & Surabaya)
(
    'WH-JKT-001', 
    'Gudang Pusat Jakarta', 
    'Jl. Raya Bekasi Km 25, Cakung, Jakarta Timur 13910', 
    'Jakarta', 
    '021-4801-2345', 
    'Bambang Suryanto', 
    'manager.jakarta@malaka.co.id',
    'main', 
    15000, 
    12500, 
    'active',
    '["Zone A - Sepatu Formal", "Zone B - Sepatu Casual", "Zone C - Sepatu Olahraga", "Zone D - Aksesoris"]',
    '{"open": "07:00", "close": "19:00", "break_start": "12:00", "break_end": "13:00"}',
    '["Loading Dock", "Climate Control", "Security Camera", "Fire System", "Forklift", "WMS System"]',
    '{"lat": -6.1751, "lng": 106.9425}'
),
(
    'WH-SBY-001', 
    'Gudang Pusat Surabaya', 
    'Jl. Rungkut Industri III No. 15, Surabaya 60293', 
    'Surabaya', 
    '031-8710-5678', 
    'Siti Nurhaliza', 
    'manager.surabaya@malaka.co.id',
    'main', 
    12000, 
    9800, 
    'active',
    '["Zone A - Ready Stock", "Zone B - Custom Order", "Zone C - Export", "Zone D - Return/Repair"]',
    '{"open": "07:00", "close": "18:00", "break_start": "12:00", "break_end": "13:00"}',
    '["Loading Dock", "Quality Control Lab", "Security System", "Packaging Area", "Cold Storage"]',
    '{"lat": -7.3346, "lng": 112.7912}'
),

-- Satellite Warehouses (Major Cities)
(
    'WH-BDG-001', 
    'Gudang Bandung', 
    'Jl. Soreang Km 8, Bandung Selatan 40911', 
    'Bandung', 
    '022-5401-9876', 
    'Ahmad Hidayat', 
    'manager.bandung@malaka.co.id',
    'satellite', 
    8000, 
    6200, 
    'active',
    '["Zone A - Retail Stock", "Zone B - Wholesale", "Zone C - Transit"]',
    '{"open": "08:00", "close": "17:00"}',
    '["Basic Security", "Manual Handling", "Local Distribution"]',
    '{"lat": -6.9734, "lng": 107.6310}'
),
(
    'WH-MDN-001', 
    'Gudang Medan', 
    'Jl. Gatot Subroto Km 6.5, Medan 20235', 
    'Medan', 
    '061-4567-1234', 
    'Dewi Sartika', 
    'manager.medan@malaka.co.id',
    'satellite', 
    6000, 
    4100, 
    'active',
    '["Zone A - Local Distribution", "Zone B - Transit Sumut"]',
    '{"open": "08:00", "close": "17:00"}',
    '["Basic Warehouse", "Local Delivery", "Security"]',
    '{"lat": 3.5952, "lng": 98.6722}'
),
(
    'WH-SMG-001', 
    'Gudang Semarang', 
    'Jl. Kaligawe Km 12, Genuk, Semarang 50117', 
    'Semarang', 
    '024-6601-5555', 
    'Rudi Hartono', 
    'manager.semarang@malaka.co.id',
    'satellite', 
    7000, 
    5300, 
    'active',
    '["Zone A - Central Java", "Zone B - Export Prep", "Zone C - Local Retail"]',
    '{"open": "07:30", "close": "17:30"}',
    '["Port Access", "Export Facility", "Container Loading"]',
    '{"lat": -6.9667, "lng": 110.4167}'
),

-- Distribution Centers
(
    'WH-DPS-001', 
    'Distribution Center Denpasar', 
    'Jl. Bypass Ngurah Rai No. 99, Denpasar 80361', 
    'Denpasar', 
    '0361-8901-777', 
    'I Made Sutrisna', 
    'manager.denpasar@malaka.co.id',
    'distribution', 
    4000, 
    2800, 
    'active',
    '["Zone A - Bali Distribution", "Zone B - Tourism Retail"]',
    '{"open": "08:00", "close": "17:00"}',
    '["Tourist Area Access", "Retail Distribution", "Local Transport Hub"]',
    '{"lat": -8.6500, "lng": 115.2167}'
),
(
    'WH-MKS-001', 
    'Distribution Center Makassar', 
    'Jl. Perintis Kemerdekaan Km 18, Makassar 90245', 
    'Makassar', 
    '0411-5678-999', 
    'Nurhayati Salim', 
    'manager.makassar@malaka.co.id',
    'distribution', 
    5000, 
    3400, 
    'active',
    '["Zone A - Sulawesi Distribution", "Zone B - Eastern Indonesia"]',
    '{"open": "08:00", "close": "17:00"}',
    '["Regional Hub", "Inter-Island Shipping", "Local Distribution"]',
    '{"lat": -5.1477, "lng": 119.4327}'
),

-- Transit Warehouses
(
    'WH-PLB-001', 
    'Transit Palembang', 
    'Jl. Lintas Sumatera Km 15, Palembang 30137', 
    'Palembang', 
    '0711-3456-888', 
    'Agus Setiawan', 
    'manager.palembang@malaka.co.id',
    'transit', 
    3000, 
    1200, 
    'active',
    '["Zone A - Transit Storage", "Zone B - Quick Distribution"]',
    '{"open": "06:00", "close": "20:00"}',
    '["24/7 Access", "Quick Turnaround", "Highway Access"]',
    '{"lat": -2.9167, "lng": 104.7458}'
),
(
    'WH-BTM-001', 
    'Transit Batam', 
    'Kawasan Industri Batamindo, Batam 29444', 
    'Batam', 
    '0778-7654-333', 
    'Linda Susanti', 
    'manager.batam@malaka.co.id',
    'transit', 
    2500, 
    800, 
    'active',
    '["Zone A - Export Processing", "Zone B - Transit"]',
    '{"open": "06:00", "close": "22:00"}',
    '["Port Access", "Export Processing", "Customs Facility"]',
    '{"lat": 1.1304, "lng": 104.0530}'
),

-- Retail Support Warehouses
(
    'WH-YGY-001', 
    'Retail Support Yogyakarta', 
    'Jl. Solo Km 8, Bantul, Yogyakarta 55184', 
    'Yogyakarta', 
    '0274-6789-444', 
    'Sri Mulyani', 
    'manager.yogyakarta@malaka.co.id',
    'retail', 
    3500, 
    2100, 
    'active',
    '["Zone A - Retail Stock", "Zone B - Tourist Products"]',
    '{"open": "08:00", "close": "17:00"}',
    '["Retail Support", "Tourist Market", "Cultural Products"]',
    '{"lat": -7.8014, "lng": 110.3641}'
),
(
    'WH-MLG-001', 
    'Retail Support Malang', 
    'Jl. Raya Tlogomas No. 246, Malang 65144', 
    'Malang', 
    '0341-5432-666', 
    'Budi Santoso', 
    'manager.malang@malaka.co.id',
    'retail', 
    2800, 
    1600, 
    'active',
    '["Zone A - University Market", "Zone B - Local Retail"]',
    '{"open": "08:00", "close": "17:00"}',
    '["University Access", "Student Market", "Local Community"]',
    '{"lat": -7.9797, "lng": 112.6304}'
),

-- Special Purpose (Maintenance/Quarantine)
(
    'WH-TNG-001', 
    'Quality Control Tangerang', 
    'Jl. MH Thamrin Km 2, Tangerang 15111', 
    'Tangerang', 
    '021-5555-2222', 
    'Hendra Wijaya', 
    'qc.tangerang@malaka.co.id',
    'quarantine', 
    1500, 
    450, 
    'active',
    '["Zone A - Incoming QC", "Zone B - Quarantine", "Zone C - Return Processing"]',
    '{"open": "08:00", "close": "16:00"}',
    '["Quality Lab", "Testing Equipment", "Quarantine Area", "Return Processing"]',
    '{"lat": -6.1783, "lng": 106.6319}'
);