-- +goose Up
CREATE TABLE transfer_orders (
    id VARCHAR(255) PRIMARY KEY,
    from_warehouse_id VARCHAR(255) NOT NULL REFERENCES warehouses(id) ON DELETE CASCADE,
    to_warehouse_id VARCHAR(255) NOT NULL REFERENCES warehouses(id) ON DELETE CASCADE,
    order_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE transfer_orders;
